<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="28" total="36" passed="5" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-31T17:41:57 IST" name="Suite_to_automate_SIM" finished-at="2024-10-31T17:44:02 IST" duration-ms="124319">
    <groups>
    </groups>
    <test started-at="2024-10-31T17:41:57 IST" name="Test" finished-at="2024-10-31T17:44:02 IST" duration-ms="124319">
      <class name="Sim_automation.EstimateCreation">
        <test-method signature="estimateform()[pri:5, instance:Sim_automation.EstimateCreation@5158b42f]" started-at="2024-10-31T17:43:33 IST" name="estimateform" description="Add a Estimate in the SIM-Web App" finished-at="2024-10-31T17:43:53 IST" duration-ms="19899" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- estimateform -->
      </class> <!-- Sim_automation.EstimateCreation -->
      <class name="Sim_automation.PaymentReceivedCreation">
        <test-method signature="paymentRecivedForm()[pri:7, instance:Sim_automation.PaymentReceivedCreation@72d1ad2e]" started-at="2024-10-31T17:43:59 IST" name="paymentRecivedForm" description="Add a Payment (Received) in the SIM-Web App" finished-at="2024-10-31T17:44:00 IST" duration-ms="1100" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Payment List Form Open expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Payment List Form Open expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at Sim_automation.PaymentReceivedCreation.paymentRecivedForm(PaymentReceivedCreation.java:16)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- paymentRecivedForm -->
      </class> <!-- Sim_automation.PaymentReceivedCreation -->
      <class name="Sim_automation.SaleOrderCreation">
        <test-method signature="saleOrderform()[pri:6, instance:Sim_automation.SaleOrderCreation@595b007d]" started-at="2024-10-31T17:43:53 IST" name="saleOrderform" description="Add a Sale Order in the SIM-Web App" finished-at="2024-10-31T17:43:58 IST" duration-ms="5063" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Create Sale Order page Open successfully expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Create Sale Order page Open successfully expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at Sim_automation.SaleOrderCreation.saleOrderform(SaleOrderCreation.java:16)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saleOrderform -->
      </class> <!-- Sim_automation.SaleOrderCreation -->
      <class name="Sim_automation.Login">
        <test-method is-config="true" signature="reportGenerate()[pri:0, instance:Sim_automation.Login@2a798d51]" started-at="2024-10-31T17:41:57 IST" name="reportGenerate" finished-at="2024-10-31T17:41:57 IST" duration-ms="196" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportGenerate -->
        <test-method is-config="true" signature="browserOpen()[pri:0, instance:Sim_automation.Login@2a798d51]" started-at="2024-10-31T17:41:57 IST" name="browserOpen" finished-at="2024-10-31T17:42:17 IST" duration-ms="19861" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserOpen -->
        <test-method signature="logindata()[pri:1, instance:Sim_automation.Login@2a798d51]" started-at="2024-10-31T17:42:17 IST" name="logindata" description="Login in the SIM-Web App" finished-at="2024-10-31T17:42:34 IST" duration-ms="17068" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logindata -->
        <test-method is-config="true" signature="logout()[pri:0, instance:Sim_automation.Login@2a798d51]" started-at="2024-10-31T17:44:01 IST" name="logout" finished-at="2024-10-31T17:44:02 IST" duration-ms="721" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="endReport()[pri:0, instance:Sim_automation.Login@2a798d51]" started-at="2024-10-31T17:44:02 IST" name="endReport" finished-at="2024-10-31T17:44:02 IST" duration-ms="301" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- Sim_automation.Login -->
      <class name="Sim_automation.PaymentPaidCreation">
        <test-method signature="paymentPecivedForm()[pri:8, instance:Sim_automation.PaymentPaidCreation@2d7275fc]" started-at="2024-10-31T17:44:00 IST" name="paymentPecivedForm" description="Add a Payment (Paid) in the SIM-Web App" finished-at="2024-10-31T17:44:01 IST" duration-ms="1069" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Payment List Form Open expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Payment List Form Open expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at Sim_automation.PaymentPaidCreation.paymentPecivedForm(PaymentPaidCreation.java:17)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- paymentPecivedForm -->
      </class> <!-- Sim_automation.PaymentPaidCreation -->
      <class name="Sim_automation.InvoiceCreation">
        <test-method signature="invoiceform()[pri:3, instance:Sim_automation.InvoiceCreation@5c5eefef]" started-at="2024-10-31T17:42:57 IST" name="invoiceform" description="Add an Invoice in the SIM-Web App" finished-at="2024-10-31T17:43:20 IST" duration-ms="22740" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invoiceform -->
      </class> <!-- Sim_automation.InvoiceCreation -->
      <class name="Sim_automation.PurchaseCreation">
        <test-method signature="purchaseform()[pri:2, instance:Sim_automation.PurchaseCreation@222545dc]" started-at="2024-10-31T17:42:34 IST" name="purchaseform" description="Add a Purchase in the SIM-Web App" finished-at="2024-10-31T17:42:57 IST" duration-ms="22802" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- purchaseform -->
      </class> <!-- Sim_automation.PurchaseCreation -->
      <class name="Sim_automation.PurchaseOrderCreation">
        <test-method signature="purchaseOrderform()[pri:4, instance:Sim_automation.PurchaseOrderCreation@16293aa2]" started-at="2024-10-31T17:43:20 IST" name="purchaseOrderform" description="Add a Purchase Order in the SIM-Web App" finished-at="2024-10-31T17:43:33 IST" duration-ms="13572" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- purchaseOrderform -->
      </class> <!-- Sim_automation.PurchaseOrderCreation -->
    </test> <!-- Test -->
  </suite> <!-- Suite_to_automate_SIM -->
</testng-results>
